#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# ifrn/2023.1/programacao_de_computadores/extras/letronas.py
# Copyright (C) 2023  Sidney Pedro
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

letras = [
"               AAA               BBBBBBBBBBBBBBBBB           CCCCCCCCCCCCCDDDDDDDDDDDDD        EEEEEEEEEEEEEEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFF        GGGGGGGGGGGGGHHHHHHHHH     HHHHHHHHHIIIIIIIIII          JJJJJJJJJJJKKKKKKKKK    KKKKKKKLLLLLLLLLLL             MMMMMMMM               MMMMMMMMNNNNNNNN        NNNNNNNN     OOOOOOOOO     PPPPPPPPPPPPPPPPP        QQQQQQQQQ     RRRRRRRRRRRRRRRRR      SSSSSSSSSSSSSSS TTTTTTTTTTTTTTTTTTTTTTTUUUUUUUU     UUUUUUUUVVVVVVVV           VVVVVVVVWWWWWWWW                           WWWWWWWWXXXXXXX       XXXXXXXYYYYYYY       YYYYYYYZZZZZZZZZZZZZZZZZZZ  1111111    222222222222222     333333333333333          444444444  555555555555555555         66666666   77777777777777777777     888888888          999999999          000000000     ",
"              A:::A              B::::::::::::::::B       CCC::::::::::::CD::::::::::::DDD     E::::::::::::::::::::EF::::::::::::::::::::F     GGG::::::::::::GH:::::::H     H:::::::HI::::::::I          J:::::::::JK:::::::K    K:::::KL:::::::::L             M:::::::M             M:::::::MN:::::::N       N::::::N   OO:::::::::OO   P::::::::::::::::P     QQ:::::::::QQ   R::::::::::::::::R   SS:::::::::::::::ST:::::::::::::::::::::TU::::::U     U::::::UV::::::V           V::::::VW::::::W                           W::::::WX:::::X       X:::::XY:::::Y       Y:::::YZ:::::::::::::::::Z 1::::::1   2:::::::::::::::22  3:::::::::::::::33       4::::::::4  5::::::::::::::::5        6::::::6    7::::::::::::::::::7   88:::::::::88      99:::::::::99      00:::::::::00   ",
"             A:::::A             B::::::BBBBBB:::::B    CC:::::::::::::::CD:::::::::::::::DD   E::::::::::::::::::::EF::::::::::::::::::::F   GG:::::::::::::::GH:::::::H     H:::::::HI::::::::I          J:::::::::JK:::::::K    K:::::KL:::::::::L             M::::::::M           M::::::::MN::::::::N      N::::::N OO:::::::::::::OO P::::::PPPPPP:::::P  QQ:::::::::::::QQ R::::::RRRRRR:::::R S:::::SSSSSS::::::ST:::::::::::::::::::::TU::::::U     U::::::UV::::::V           V::::::VW::::::W                           W::::::WX:::::X       X:::::XY:::::Y       Y:::::YZ:::::::::::::::::Z1:::::::1   2::::::222222:::::2 3::::::33333::::::3     4:::::::::4  5::::::::::::::::5       6::::::6     7::::::::::::::::::7 88:::::::::::::88  99:::::::::::::99  00:::::::::::::00 ",
"            A:::::::A            BB:::::B     B:::::B  C:::::CCCCCCCC::::CDDD:::::DDDDD:::::D  EE::::::EEEEEEEEE::::EFF::::::FFFFFFFFF::::F  G:::::GGGGGGGG::::GHH::::::H     H::::::HHII::::::II          JJ:::::::JJK:::::::K   K::::::KLL:::::::LL             M:::::::::M         M:::::::::MN:::::::::N     N::::::NO:::::::OOO:::::::OPP:::::P     P:::::PQ:::::::QQQ:::::::QRR:::::R     R:::::RS:::::S     SSSSSSST:::::TT:::::::TT:::::TUU:::::U     U:::::UUV::::::V           V::::::VW::::::W                           W::::::WX::::::X     X::::::XY::::::Y     Y::::::YZ:::ZZZZZZZZ:::::Z 111:::::1   2222222     2:::::2 3333333     3:::::3    4::::44::::4  5:::::555555555555      6::::::6      777777777777:::::::78::::::88888::::::89::::::99999::::::90:::::::000:::::::0",
"           A:::::::::A             B::::B     B:::::B C:::::C       CCCCCC  D:::::D    D:::::D   E:::::E       EEEEEE  F:::::F       FFFFFF G:::::G       GGGGGG  H:::::H     H:::::H    I::::I              J:::::J  KK::::::K  K:::::KKK  L:::::L               M::::::::::M       M::::::::::MN::::::::::N    N::::::NO::::::O   O::::::O  P::::P     P:::::PQ::::::Q   Q::::::Q  R::::R     R:::::RS:::::S            TTTTTT  T:::::T  TTTTTT U:::::U     U:::::U  V:::::V           V:::::V  W:::::W           WWWWW           W:::::W XXX:::::X   X:::::XXXYYY:::::Y   Y:::::YYYZZZZZ     Z:::::Z     1::::1               2:::::2             3:::::3   4::::4 4::::4  5:::::5                6::::::6                  7::::::7 8:::::8     8:::::89:::::9     9:::::90::::::0   0::::::0",
"          A:::::A:::::A            B::::B     B:::::BC:::::C                D:::::D     D:::::D  E:::::E               F:::::F             G:::::G                H:::::H     H:::::H    I::::I              J:::::J    K:::::K K:::::K     L:::::L               M:::::::::::M     M:::::::::::MN:::::::::::N   N::::::NO:::::O     O:::::O  P::::P     P:::::PQ:::::Q     Q:::::Q  R::::R     R:::::RS:::::S                    T:::::T         U:::::U     U:::::U   V:::::V         V:::::V    W:::::W         W:::::W         W:::::W     X:::::X X:::::X      Y:::::Y Y:::::Y           Z:::::Z       1::::1               2:::::2             3:::::3  4::::4  4::::4  5:::::5               6::::::6                  7::::::7  8:::::8     8:::::89:::::9     9:::::90:::::0     0:::::0",
"         A:::::A A:::::A           B::::BBBBBB:::::B C:::::C                D:::::D     D:::::D  E::::::EEEEEEEEEE     F::::::FFFFFFFFFF   G:::::G                H::::::HHHHH::::::H    I::::I              J:::::J    K::::::K:::::K      L:::::L               M:::::::M::::M   M::::M:::::::MN:::::::N::::N  N::::::NO:::::O     O:::::O  P::::PPPPPP:::::P Q:::::Q     Q:::::Q  R::::RRRRRR:::::R  S::::SSSS                 T:::::T         U:::::U     U:::::U    V:::::V       V:::::V      W:::::W       W:::::::W       W:::::W       X:::::X:::::X        Y:::::Y:::::Y           Z:::::Z        1::::1            2222::::2      33333333:::::3  4::::4   4::::4  5:::::5555555555     6::::::6                  7::::::7    8:::::88888:::::8  9:::::99999::::::90:::::0     0:::::0",
"        A:::::A   A:::::A          B:::::::::::::BB  C:::::C                D:::::D     D:::::D  E:::::::::::::::E     F:::::::::::::::F   G:::::G    GGGGGGGGGG  H:::::::::::::::::H    I::::I              J:::::j    K:::::::::::K       L:::::L               M::::::M M::::M M::::M M::::::MN::::::N N::::N N::::::NO:::::O     O:::::O  P:::::::::::::PP  Q:::::Q     Q:::::Q  R:::::::::::::RR    SS::::::SSSSS            T:::::T         U:::::U     U:::::U     V:::::V     V:::::V        W:::::W     W:::::::::W     W:::::W         X:::::::::X          Y:::::::::Y           Z:::::Z         1::::l       22222::::::22       3:::::::::::3  4::::444444::::4445:::::::::::::::5   6::::::::66666            7::::::7      8:::::::::::::8    99::::::::::::::90:::::0 000 0:::::0",
"       A:::::A     A:::::A         B::::BBBBBB:::::B C:::::C                D:::::D     D:::::D  E:::::::::::::::E     F:::::::::::::::F   G:::::G    G::::::::G  H:::::::::::::::::H    I::::I              J:::::J    K:::::::::::K       L:::::L               M::::::M  M::::M::::M  M::::::MN::::::N  N::::N:::::::NO:::::O     O:::::O  P::::PPPPPPPPP    Q:::::Q     Q:::::Q  R::::RRRRRR:::::R     SSS::::::::SS          T:::::T         U:::::U     U:::::U      V:::::V   V:::::V          W:::::W   W:::::W:::::W   W:::::W          X:::::::::X           Y:::::::Y           Z:::::Z          1::::l     22::::::::222         33333333:::::3 4::::::::::::::::4555555555555:::::5 6::::::::::::::66         7::::::7      8:::::88888:::::8     99999::::::::9 0:::::0 000 0:::::0",
"      A:::::AAAAAAAAA:::::A        B::::B     B:::::BC:::::C                D:::::D     D:::::D  E::::::EEEEEEEEEE     F::::::FFFFFFFFFF   G:::::G    GGGGG::::G  H::::::HHHHH::::::H    I::::I  JJJJJJJ     J:::::J    K::::::K:::::K      L:::::L               M::::::M   M:::::::M   M::::::MN::::::N   N:::::::::::NO:::::O     O:::::O  P::::P            Q:::::Q     Q:::::Q  R::::R     R:::::R       SSSSSS::::S         T:::::T         U:::::U     U:::::U       V:::::V V:::::V            W:::::W W:::::W W:::::W W:::::W          X:::::X:::::X           Y:::::Y           Z:::::Z           1::::l    2:::::22222                    3:::::34444444444:::::444            5:::::56::::::66666:::::6       7::::::7      8:::::8     8:::::8         9::::::9  0:::::0     0:::::0",
"     A:::::::::::::::::::::A       B::::B     B:::::BC:::::C                D:::::D     D:::::D  E:::::E               F:::::F             G:::::G        G::::G  H:::::H     H:::::H    I::::I  J:::::J     J:::::J    K:::::K K:::::K     L:::::L               M::::::M    M:::::M    M::::::MN::::::N    N::::::::::NO:::::O     O:::::O  P::::P            Q:::::Q  QQQQ:::::Q  R::::R     R:::::R            S:::::S        T:::::T         U:::::U     U:::::U        V:::::V:::::V              W:::::W:::::W   W:::::W:::::W          X:::::X X:::::X          Y:::::Y          Z:::::Z            1::::l   2:::::2                         3:::::3          4::::4              5:::::56:::::6     6:::::6     7::::::7       8:::::8     8:::::8        9::::::9   0:::::0     0:::::0",
"    A:::::AAAAAAAAAAAAA:::::A      B::::B     B:::::B C:::::C       CCCCCC  D:::::D    D:::::D   E:::::E       EEEEEE  F:::::F              G:::::G       G::::G  H:::::H     H:::::H    I::::I  J::::::J   J::::::J  KK::::::K  K:::::KKK  L:::::L         LLLLLLM::::::M     MMMMM     M::::::MN::::::N     N:::::::::NO::::::O   O::::::O  P::::P            Q::::::Q Q::::::::Q  R::::R     R:::::R            S:::::S        T:::::T         U::::::U   U::::::U         V:::::::::V                W:::::::::W     W:::::::::W        XXX:::::X   X:::::XXX       Y:::::Y       ZZZ:::::Z     ZZZZZ   1::::l   2:::::2                         3:::::3          4::::4  5555555     5:::::56:::::6     6:::::6    7::::::7        8:::::8     8:::::8       9::::::9    0::::::0   0::::::0",
"   A:::::A             A:::::A   BB:::::BBBBBB::::::B  C:::::CCCCCCCC::::CDDD:::::DDDDD:::::D  EE::::::EEEEEEEE:::::EFF:::::::FF             G:::::GGGGGGGG::::GHH::::::H     H::::::HHII::::::IIJ:::::::JJJ:::::::J  K:::::::K   K::::::KLL:::::::LLLLLLLLL:::::LM::::::M               M::::::MN::::::N      N::::::::NO:::::::OOO:::::::OPP::::::PP          Q:::::::QQ::::::::QRR:::::R     R:::::RSSSSSSS     S:::::S      TT:::::::TT       U:::::::UUU:::::::U          V:::::::V                  W:::::::W       W:::::::W         X::::::X     X::::::X       Y:::::Y       Z::::::ZZZZZZZZ:::Z111::::::1112:::::2       2222223333333     3:::::3          4::::4  5::::::55555::::::56::::::66666::::::6   7::::::7         8::::::88888::::::8      9::::::9     0:::::::000:::::::0",
"  A:::::A               A:::::A  B:::::::::::::::::B    CC:::::::::::::::CD:::::::::::::::DD   E::::::::::::::::::::EF::::::::FF              GG:::::::::::::::GH:::::::H     H:::::::HI::::::::I JJ:::::::::::::JJ   K:::::::K    K:::::KL::::::::::::::::::::::LM::::::M               M::::::MN::::::N       N:::::::N OO:::::::::::::OO P::::::::P           QQ::::::::::::::Q R::::::R     R:::::RS::::::SSSSSS:::::S      T:::::::::T        UU:::::::::::::UU            V:::::V                    W:::::W         W:::::W          X:::::X       X:::::X    YYYY:::::YYYY    Z:::::::::::::::::Z1::::::::::12::::::2222222:::::23::::::33333::::::3        44::::::44 55:::::::::::::55  66:::::::::::::66   7::::::7           88:::::::::::::88      9::::::9       00:::::::::::::00 ",
" A:::::A                 A:::::A B::::::::::::::::B       CCC::::::::::::CD::::::::::::DDD     E::::::::::::::::::::EF::::::::FF                GGG::::::GGG:::GH:::::::H     H:::::::HI::::::::I   JJ:::::::::JJ     K:::::::K    K:::::KL::::::::::::::::::::::LM::::::M               M::::::MN::::::N        N::::::N   OO:::::::::OO   P::::::::P             QQ:::::::::::Q  R::::::R     R:::::RS:::::::::::::::SS       T:::::::::T          UU:::::::::UU               V:::V                      W:::W           W:::W           X:::::X       X:::::X    Y:::::::::::Y    Z:::::::::::::::::Z1::::::::::12::::::::::::::::::23:::::::::::::::33         4::::::::4   55:::::::::55      66:::::::::66    7::::::7              88:::::::::88       9::::::9          00:::::::::00   ",
"AAAAAAA                   AAAAAAABBBBBBBBBBBBBBBBB           CCCCCCCCCCCCCDDDDDDDDDDDDD        EEEEEEEEEEEEEEEEEEEEEEFFFFFFFFFFF                   GGGGGG   GGGGHHHHHHHHH     HHHHHHHHHIIIIIIIIII     JJJJJJJJJ       KKKKKKKKK    KKKKKKKLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMM               MMMMMMMMNNNNNNNN         NNNNNNN     OOOOOOOOO     PPPPPPPPPP               QQQQQQQQ::::QQRRRRRRRR     RRRRRRR SSSSSSSSSSSSSSS         TTTTTTTTTTT            UUUUUUUUU                  VVV                        WWW             WWW            XXXXXXX       XXXXXXX    YYYYYYYYYYYYY    ZZZZZZZZZZZZZZZZZZZ11111111111122222222222222222222 333333333333333           4444444444     555555555          666666666     77777777                 888888888        99999999             000000000     "]

string = input("Digite algo: ").upper()

cada_letra = []

for letra in string:
    inicio = len(letras[0])
    fim = 0

    menor_inicio = inicio
    maior_fim = fim

    for linha in letras:
        inicio = linha.find(letra)
        if (inicio < menor_inicio):
            menor_inicio = inicio

        fim = linha.rfind(letra)
        if (fim > maior_fim):
            maior_fim = fim

    cada_letra.append([menor_inicio, maior_fim + 1])

# print(cada_letra)

for linha in range(len(letras)):
    for letra in range(len(string)):
        print(letras[linha][cada_letra[letra][0]:cada_letra[letra][1]], end='')

    print()
